name: bmf-playground
channels:
    - conda-forge
    - pytorch
dependencies:
    - numpy
    - matplotlib
    - scikit-learn
    - uproot
    - awkward
    - root
    - pytorch
    - hist
    - jupyter